# This is my backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "contact-backend-deployment"
spec:
  #Pod replicas
  replicas: 1
  selector:
    matchLabels:
      component: contacts-backend
  template:
    metadata:
      labels:
        component: contacts-backend
    spec:
      containers:
        - name: contacts-api
          #pod image must be pulled from my dockerhub
          image: ghaithmlika/contact-backend
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_HOST
              value: contacts-mango-cluster-ip-service
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
