# This is my service for the backend pod
# it listens on port 8080 and forwards traffic to port 8080
apiVersion: v1
kind: Service
metadata:
  name: contact-backend-server-cluster-ip
spec:
  type: ClusterIP
  # the name of the pod to be associated with
  selector:
    component: contacts-backend
  ports:
    - port: 8080
      targetPort: 8080
