apiVersion: v1
# indicate that this is a secret file
kind: Secret
metadata:
  name: mongo-secret
# how we define secret data
# Opaque : the default type key:value pairs
type: Opaque
# database credentials coded in base64
data:
  mongo-user: c3VwZXJBZG1pbg==
  mongo-password: YWRtaW4xMjM=
